# Generated by Django 3.2 on 2021-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=200, verbose_name='Токен')),
                ('tg_chat_id', models.CharField(max_length=200, verbose_name='Чат в телеграмме')),
                ('tg_message', models.TextField(verbose_name='Текст заявки')),
            ],
            options={
                'verbose_name': 'Настройка сообщения',
                'verbose_name_plural': 'Настройки сообщений',
            },
        ),
    ]
